## theme.rpy - Generated by Preset Editor Game Configurator
## This file overrides default gui.rpy and options.rpy settings
## Delete this file to revert to Ren'Py defaults
##
## Generated: 2026-01-21 15:29:53

init offset = 1  # Load after gui.rpy


################################################################################
## Project
################################################################################

define config.name = _("TEST NAME GAME")
define config.version = "0.1.0"
define build.name = "MyStoryGame"
define config.save_directory = "mystorygame-saves"


################################################################################
## Screen Dimensions
################################################################################

define config.screen_width = 1920
define config.screen_height = 1080
define config.physical_width = 960
define config.physical_height = 540


################################################################################
## Colors
################################################################################

define gui.accent_color = '#0099ccff'
define gui.hover_color = '#66c1e0ff'
define gui.idle_color = '#888888ff'
define gui.idle_small_color = '#aaaaaaff'
define gui.selected_color = '#ffffffff'
define gui.insensitive_color = '#8888887f'
define gui.text_color = '#ffffffff'
define gui.interface_text_color = '#ffffffff'
define gui.muted_color = '#003d51ff'
define gui.hover_muted_color = '#005b7aff'


################################################################################
## Fonts
################################################################################

define gui.text_font = "Jua-Regular.ttf"
define gui.name_text_font = "Jua-Regular.ttf"
define gui.interface_text_font = "CalSans-Regular.ttf"


################################################################################
## Font Sizes
################################################################################

define gui.text_size = 48
define gui.name_text_size = 30
define gui.interface_text_size = 28
define gui.label_text_size = 30
define gui.notify_text_size = 20
define gui.title_text_size = 60


################################################################################
## Dialogue Box Layout
################################################################################

define gui.textbox_height = 185
define gui.textbox_yalign = 0.5
define gui.dialogue_xpos = 268
define gui.dialogue_ypos = 50
define gui.dialogue_width = 744
define gui.dialogue_text_xalign = 0.0


################################################################################
## Name Box Layout
################################################################################

define gui.name_xpos = 240
define gui.name_ypos = 0
define gui.name_xalign = 0.0
# gui.namebox_width = None (using default)
# gui.namebox_height = None (using default)


################################################################################
## Menu Backgrounds
################################################################################

define gui.main_menu_background = "gui/main_menu.png"
define gui.game_menu_background = "gui/game_menu.png"


################################################################################
## Text Speed
################################################################################

default preferences.text_cps = 40
default preferences.afm_time = 15


################################################################################
## Window Behavior
################################################################################

define config.quit_action = Quit(confirm=True)
define gui.QUIT = _("Are you sure you want to quit?\n\nAny unsaved progress will be lost.")


################################################################################
## UI Details
################################################################################

define gui.bar_size = 22
define gui.scrollbar_size = 11
define gui.slider_size = 22
# gui.button_width = None (using default)
# gui.button_height = None (using default)


################################################################################
## Choice Buttons
################################################################################

define gui.choice_button_width = 667
# gui.choice_button_height = None (using default)
define gui.choice_button_text_idle_color = '#888888'
define gui.choice_button_text_hover_color = '#ffffff'
define gui.choice_button_text_insensitive_color = '#8888887f'
define gui.choice_spacing = 19
