## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## Testing 1 preset combinations

label preset_demo:
    scene bg_demo with dissolve

    "Preset Demo - Select a preset to test"

    menu preset_demo_menu:
        "Select a preset to demo:"

        "1. preset_edge_left_enter(), shader_glow_purple":
            show char_demo at preset_edge_left_enter(), shader_glow_purple
            test "preset_edge_left_enter(), shader_glow_purple"
            pause 0.5
            hide char_demo with dissolve
            jump preset_demo

        "Exit Demo":
            "Demo complete!"
            return
