## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## Testing 1 preset combinations

label preset_demo:
    scene bg_demo with dissolve

    "Preset Demo - Select a preset to test"

    menu preset_demo_menu:
        "Select a preset to demo:"

        "1. preset_pop_in_enter(), shader_magic_spinner":
            show char_demo at preset_pop_in_enter(), shader_magic_spinner
            test "preset_pop_in_enter(), shader_magic_spinner"
            pause 0.5
            hide char_demo with dissolve
            jump preset_demo

        "Exit Demo":
            "Demo complete!"
            return
