## options.rpy - Generated by Preset Editor
##
## Screen dimensions for demo testing

define config.screen_width = 1080
define config.screen_height = 1920

define config.name = "Preset Editor Demo"
define config.save_directory = "preset_editor_demo"
