## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## Testing 1 preset combinations
## Apply to dialog: True

label preset_demo:
    scene bg_demo with dissolve

    "Preset Demo - Select a preset to test"

    menu preset_demo_menu:
        "Select a preset to demo:"

        "1. T:spin_enter + S:glitch_light + TS:wave_dreamy":
            show dialog_demo at preset_spin_enter(), shader_glitch_light:
                xalign 0.5
                yalign 0.9
            "Sample dialogue text for testing presets."
            hide dialog_demo with dissolve
            jump preset_demo

        "Exit Demo":
            "Demo complete!"
            return
