## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## Testing 1 preset combinations
## Mode: Dialog/Text Shader Testing

label preset_demo:
    scene bg_demo with dissolve

    "Preset Demo - Select a preset to test"

    menu preset_demo_menu:
        "Select a preset to demo:"

        "1. T:spin_enter + S:glitch_light + TS:wave_dreamy":
            $ demo_dialog_transform = shader_glitch_light
            "{shader=wave:u__amplitude=3.0:u__frequency=2.0}Sample dialogue text for testing presets.{/shader}"
            $ demo_dialog_transform = None
            jump preset_demo

        "Exit Demo":
            "Demo complete!"
            return
