## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## Testing 1 preset combinations
## Mode: Dialog Testing (shader on dialog artwork + text shader)

label preset_demo:
    scene bg_demo with dissolve

    "Preset Demo - Select a preset to test"

    menu preset_demo_menu:
        "Select a preset to demo:"

        "1. T:spin_enter + S:glitch_light + TS:wavy gravy":
            $ demo_dialog_background = "images/dialog_demo.png"
            $ demo_dialog_transform = shader_glitch_light
            "{color=#420505}{font=CalSans-Regular.ttf}{size=37}{shader=wave}Sample dialogue text for testing presets.{/shader}{/size}{/font}{/color}"
            $ demo_dialog_transform = None
            $ demo_dialog_background = None
            jump preset_demo

        "Exit Demo":
            "Demo complete!"
            return
