## script.rpy - Generated by Preset Editor
##
## Demo game setup
## Uses real Ren'Py game patterns - no fake overlay images

define test = Character("Test")

# Background stretched to fit screen dimensions
image bg_demo = im.Scale("images/bg_demo.png", 1080, 1920)

# Character image
image char_demo = "images/char_demo.png"

# Note: Dialog box shaders are applied to the actual say screen window
# via demo_dialog_transform variable (see screens.rpy)

label start:
    jump preset_demo
