## script.rpy - Generated by Preset Editor
##
## Demo game setup
## Uses real Ren'Py game patterns via the say screen

define test = Character("Test")

# Background stretched to fit screen dimensions
image bg_demo = im.Scale("images/bg_demo.png", 1080, 1920)

# Character image
image char_demo = "images/char_demo.png"

# Dialog artwork for "Apply to dialog" mode
# Used as window background instead of black rect
# Path: images/dialog_demo.png

# Note: Dialog shaders are applied to the actual say screen window
# via demo_dialog_transform variable (see screens.rpy)
# Dialog background is set via demo_dialog_background variable

label start:
    jump preset_demo
