## script.rpy - Generated by Preset Editor
##
## Demo game setup

define test = Character("Test")

# Background stretched to fit screen dimensions
image bg_demo = im.Scale("images/bg_demo.png", 1080, 1920)

# Character image
image char_demo = "images/char_demo.png"

# Dialog box image for demo - scaled to proper dialog dimensions
# Width: 1000px (leaves margins on 1080 screen), Height: 250px (typical dialog box)
image dialog_demo = im.Scale("images/dialog_demo.png", 1000, 250)

label start:
    jump preset_demo
