"""
demo_generator.py - Generate Ren'Py test scripts for presets

Creates menu-based demo scripts that test preset combinations.
"""

import os
from pathlib import Path
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class DemoItem:
    """A single demo item (transition + shader combination)."""
    transition: Optional[str] = None
    shader: Optional[str] = None

    @property
    def display_name(self) -> str:
        """Get display name for the demo item."""
        parts = []
        if self.transition:
            parts.append(f"preset_{self.transition}()")
        if self.shader:
            parts.append(f"shader_{self.shader}")
        return ", ".join(parts) if parts else "(empty)"

    @property
    def at_clause(self) -> str:
        """Get the 'at' clause for Ren'Py show statement."""
        parts = []
        if self.transition:
            parts.append(f"preset_{self.transition}()")
        if self.shader:
            parts.append(f"shader_{self.shader}")
        return ", ".join(parts) if parts else "center"

    def is_empty(self) -> bool:
        """Check if the item has no presets."""
        return not self.transition and not self.shader


class DemoGenerator:
    """
    Generates Ren'Py demo scripts for testing presets.

    Features:
    - Menu-based navigation (max 10 items)
    - Tests transition + shader combinations
    - Configurable character and background
    """

    MAX_ITEMS = 10

    def __init__(self):
        self.items: List[DemoItem] = []
        self.character_name = "novy"
        self.character_image = "novy front"
        self.background = "bg_street"
        self.label_name = "preset_demo"

    def add_item(self, transition: Optional[str], shader: Optional[str]) -> bool:
        """
        Add a demo item.

        Returns False if max items reached.
        """
        if len(self.items) >= self.MAX_ITEMS:
            return False

        item = DemoItem(transition=transition, shader=shader)
        if not item.is_empty():
            self.items.append(item)
            return True
        return False

    def remove_item(self, index: int) -> bool:
        """Remove a demo item by index."""
        if 0 <= index < len(self.items):
            self.items.pop(index)
            return True
        return False

    def clear_items(self):
        """Clear all demo items."""
        self.items.clear()

    def move_item(self, index: int, direction: str) -> bool:
        """Move an item up or down."""
        if direction == "up" and index > 0:
            self.items[index], self.items[index - 1] = self.items[index - 1], self.items[index]
            return True
        elif direction == "down" and index < len(self.items) - 1:
            self.items[index], self.items[index + 1] = self.items[index + 1], self.items[index]
            return True
        return False

    def get_item(self, index: int) -> Optional[DemoItem]:
        """Get a demo item by index."""
        if 0 <= index < len(self.items):
            return self.items[index]
        return None

    def generate_script(self) -> str:
        """
        Generate the Ren'Py demo script.

        Returns the script content as a string.
        """
        if not self.items:
            return self._generate_empty_script()

        lines = [
            "## preset_demo.rpy - Auto-generated preset demo",
            "## Generated by Preset Editor",
            "##",
            f"## Testing {len(self.items)} preset combinations",
            "",
            f"label {self.label_name}:",
            f"    scene {self.background} with dissolve",
            "",
            '    "Preset Demo - Select a preset to test"',
            "",
        ]

        # Generate menu
        lines.append("    menu preset_demo_menu:")
        lines.append('        "Select a preset to demo:"')
        lines.append("")

        for i, item in enumerate(self.items):
            menu_label = item.display_name.replace('"', '\\"')
            at_clause = item.at_clause

            lines.append(f'        "{i+1}. {menu_label}":')
            lines.append(f"            show {self.character_image} at {at_clause}")
            lines.append(f'            {self.character_name} "{at_clause}"')
            lines.append(f"            pause 0.5")
            lines.append(f"            hide {self.character_name.split()[0]} with dissolve")
            lines.append(f"            jump {self.label_name}")
            lines.append("")

        # Exit option
        lines.append('        "Exit Demo":')
        lines.append('            "Demo complete!"')
        lines.append("            return")
        lines.append("")

        return "\n".join(lines)

    def _generate_empty_script(self) -> str:
        """Generate a placeholder script when no items."""
        return f'''## preset_demo.rpy - Auto-generated preset demo
## Generated by Preset Editor
##
## No preset combinations selected.

label {self.label_name}:
    scene {self.background} with dissolve

    "No presets selected for demo."
    "Use the Preset Editor to add demo items."

    return
'''

    def save_script(self, output_path: str) -> bool:
        """
        Save the demo script to a file.

        Args:
            output_path: Path to save the script

        Returns:
            True if successful, False otherwise
        """
        try:
            # Ensure directory exists
            output_dir = os.path.dirname(output_path)
            if output_dir:
                Path(output_dir).mkdir(parents=True, exist_ok=True)

            script = self.generate_script()
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(script)
            return True
        except Exception as e:
            print(f"DemoGenerator: Error saving script: {e}")
            return False

    def generate_test_game_script(self) -> str:
        """
        Generate a complete test game script.rpy.

        This is for the standalone test game folder.
        """
        lines = [
            "## script.rpy - Test game for Preset Editor",
            "##",
            "## This is a minimal Ren'Py game for testing presets.",
            "## Generated by Preset Editor.",
            "",
            "# Character definition",
            f'define {self.character_name} = Character("{self.character_name.title()}")',
            "",
            "# Background (use a solid color if no image)",
            f'image {self.background} = Solid("#333333")',
            "",
            "# Character placeholder",
            f'image {self.character_image} = Solid("#666666", xsize=400, ysize=800)',
            "",
            "label start:",
            '    "Welcome to the Preset Editor Test Game!"',
            '    "Use this to test your preset combinations."',
            "",
            f"    jump {self.label_name}",
            "",
        ]

        # Add the demo script content
        lines.append(self.generate_script())

        return "\n".join(lines)

    def save_test_game(self, game_folder: str) -> bool:
        """
        Save a complete test game to a folder.

        Creates script.rpy and options.rpy.
        """
        try:
            game_path = Path(game_folder)
            game_path.mkdir(parents=True, exist_ok=True)

            # script.rpy
            script_path = game_path / "script.rpy"
            with open(script_path, 'w', encoding='utf-8') as f:
                f.write(self.generate_test_game_script())

            # options.rpy (minimal)
            options_path = game_path / "options.rpy"
            with open(options_path, 'w', encoding='utf-8') as f:
                f.write('''## options.rpy - Test game configuration

define config.name = "Preset Editor Test"
define build.name = "PresetTest"
define config.version = "1.0"

define config.screen_width = 1920
define config.screen_height = 1080

define config.save_directory = "preset_editor_test"
''')

            return True
        except Exception as e:
            print(f"DemoGenerator: Error saving test game: {e}")
            return False
