"""
dialogbox_generator.py - Code generation for Dialog Box Maker tab

Generates Ren'Py code for Frame-based dialog boxes with 9-slice borders,
positioning, and sizing properties.
"""

from dataclasses import dataclass
from typing import Optional
from pathlib import Path


@dataclass
class DialogBoxConfig:
    """Configuration for a dialog box style."""
    # Style
    style_name: str = "window"

    # Image
    image_path: str = ""

    # Frame borders (9-slice)
    border_left: int = 0
    border_top: int = 0
    border_right: int = 0
    border_bottom: int = 0
    tile: bool = False

    # Positioning
    xalign: float = 0.5
    yalign: float = 1.0

    # Sizing
    xsize: int = 0  # 0 = auto
    ysize: int = 185
    xfill: bool = True


class DialogBoxGenerator:
    """Generates Ren'Py code for dialog box configurations."""

    def __init__(self):
        pass

    def generate_frame_code(self, config: DialogBoxConfig) -> str:
        """Generate just the Frame() displayable code."""
        if not config.image_path:
            return "# No image specified"

        # Build Borders
        borders = f"Borders({config.border_left}, {config.border_top}, {config.border_right}, {config.border_bottom})"

        # Build Frame with optional tile parameter
        if config.tile:
            return f'Frame("{config.image_path}", {borders}, tile=True)'
        else:
            return f'Frame("{config.image_path}", {borders})'

    def generate_style_background(self, config: DialogBoxConfig) -> str:
        """Generate style block with just the background."""
        frame_code = self.generate_frame_code(config)

        lines = [
            f"style {config.style_name}:",
            f"    background {frame_code}"
        ]

        return "\n".join(lines)

    def generate_full_style(self, config: DialogBoxConfig) -> str:
        """Generate complete style block with all properties."""
        frame_code = self.generate_frame_code(config)

        lines = [
            f"style {config.style_name}:",
            f"    background {frame_code}",
            f"    xalign {config.xalign}",
            f"    yalign {config.yalign}",
        ]

        # Add xsize if specified (non-zero)
        if config.xsize > 0:
            lines.append(f"    xsize {config.xsize}")

        # Add ysize if specified (non-zero)
        if config.ysize > 0:
            lines.append(f"    ysize {config.ysize}")

        # Add xfill
        if config.xfill:
            lines.append("    xfill True")

        return "\n".join(lines)

    def generate_code(self, config: DialogBoxConfig, format_type: str = "full") -> str:
        """
        Generate code based on format type.

        Args:
            config: DialogBoxConfig with all settings
            format_type: One of "inline", "background", "full"

        Returns:
            Generated Ren'Py code string
        """
        if format_type == "inline":
            return self.generate_frame_code(config)
        elif format_type == "background":
            return self.generate_style_background(config)
        elif format_type == "full":
            return self.generate_full_style(config)
        else:
            return self.generate_full_style(config)

    def generate_demo_script(self, config: DialogBoxConfig, game_folder: str) -> str:
        """
        Generate a Ren'Py demo script to preview the dialog box.

        Args:
            config: DialogBoxConfig with all settings
            game_folder: Path to game folder for relative paths

        Returns:
            Complete Ren'Py script content
        """
        # Convert image path to be relative to game folder if needed
        image_path = config.image_path
        if image_path and not image_path.startswith("gui/"):
            # Keep absolute path for demo, Ren'Py will handle it
            pass

        frame_code = self.generate_frame_code(config)

        script = f'''## dialogbox_demo.rpy - Generated by Dialog Box Maker
## This file is auto-generated. Do not edit manually.

init python:
    # Store the demo config
    dialogbox_demo_active = True

# Override the window style for demo
style dialogbox_demo_window:
    background {frame_code}
    xalign {config.xalign}
    yalign {config.yalign}
'''

        if config.xsize > 0:
            script += f"    xsize {config.xsize}\n"

        if config.ysize > 0:
            script += f"    ysize {config.ysize}\n"

        if config.xfill:
            script += "    xfill True\n"

        script += f'''
# Demo screen to show the dialog box
screen dialogbox_demo_screen():

    # Info overlay
    vbox:
        xalign 0.0
        yalign 0.0
        xoffset 20
        yoffset 20

        text "Dialog Box Preview" size 24 color "#ffffff"
        text "Style: {config.style_name}" size 18 color "#aaaaaa"
        text "Borders: L={config.border_left} T={config.border_top} R={config.border_right} B={config.border_bottom}" size 16 color "#888888"
        text "Position: xalign={config.xalign} yalign={config.yalign}" size 16 color "#888888"
        null height 20
        text "Press SPACE or click to exit" size 16 color "#666666"

    # The actual dialog box preview
    window:
        style "dialogbox_demo_window"

        vbox:
            xalign 0.5
            yalign 0.5

            text "Character Name" size 28 color "#ffcc00"
            null height 10
            text "This is sample dialogue text to preview how your dialog box will look with actual content. The text should wrap naturally within the box boundaries." size 22 color "#ffffff"

    # Click to exit
    key "K_SPACE" action Return()
    button:
        xfill True
        yfill True
        action Return()
        background None

label dialogbox_demo:
    call screen dialogbox_demo_screen
    return
'''

        return script

    def write_demo_script(self, config: DialogBoxConfig, game_folder: str) -> bool:
        """
        Write the demo script to the game folder.

        Args:
            config: DialogBoxConfig with all settings
            game_folder: Path to game folder

        Returns:
            True if successful, False otherwise
        """
        try:
            script_content = self.generate_demo_script(config, game_folder)
            demo_path = Path(game_folder) / "dialogbox_demo.rpy"

            with open(demo_path, 'w', encoding='utf-8') as f:
                f.write(script_content)

            print(f"[DialogBoxGenerator] Wrote demo to: {demo_path}")
            return True

        except Exception as e:
            print(f"[DialogBoxGenerator] Error writing demo: {e}")
            return False
