"""
gameconfig_manager.py - Game configuration management

Handles:
- Loading/saving baseline_config.json
- Generating theme.rpy code for Ren'Py games
- Configuration validation
"""

import json
import os
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, Optional, Callable, List
from copy import deepcopy


class GameConfigManager:
    """Manages game configuration loading, saving, and code generation."""

    def __init__(self):
        self._config: Dict[str, Any] = {}
        self._config_path: Optional[str] = None
        self._change_callbacks: List[Callable] = []
        self._dirty = False

        # Set default path to baseline_config.json next to this module
        module_dir = Path(__file__).parent
        self._config_path = str(module_dir / "baseline_config.json")

    def set_path(self, path: str):
        """Set the config file path."""
        self._config_path = path

    def load(self) -> bool:
        """Load configuration from JSON file."""
        if not self._config_path or not Path(self._config_path).exists():
            print(f"Config file not found: {self._config_path}")
            return False

        try:
            with open(self._config_path, 'r', encoding='utf-8') as f:
                self._config = json.load(f)
            self._dirty = False
            print(f"Loaded config from: {self._config_path}")
            return True
        except Exception as e:
            print(f"Error loading config: {e}")
            return False

    def save(self) -> bool:
        """Save configuration to JSON file."""
        if not self._config_path:
            print("No config path set")
            return False

        try:
            with open(self._config_path, 'w', encoding='utf-8') as f:
                json.dump(self._config, f, indent=2)
            self._dirty = False
            print(f"Saved config to: {self._config_path}")
            return True
        except Exception as e:
            print(f"Error saving config: {e}")
            return False

    def on_change(self, callback: Callable):
        """Register a callback for when config changes."""
        if callback not in self._change_callbacks:
            self._change_callbacks.append(callback)

    def _notify_change(self):
        """Notify all registered callbacks of a change."""
        self._dirty = True
        for cb in self._change_callbacks:
            try:
                cb()
            except Exception as e:
                print(f"Change callback error: {e}")

    # =========================================================================
    # Getters - Get entire sections or specific values
    # =========================================================================

    def get_config(self) -> Dict[str, Any]:
        """Get the entire configuration."""
        return deepcopy(self._config)

    def get_section(self, section: str) -> Optional[Dict[str, Any]]:
        """Get a configuration section."""
        return deepcopy(self._config.get(section))

    def get_value(self, section: str, key: str) -> Any:
        """Get a specific value from a section."""
        sect = self._config.get(section, {})
        return sect.get(key)

    # =========================================================================
    # Setters - Set entire sections or specific values
    # =========================================================================

    def set_section(self, section: str, data: Dict[str, Any]):
        """Set an entire section."""
        self._config[section] = deepcopy(data)
        self._notify_change()
        self.save()  # Auto-save

    def set_value(self, section: str, key: str, value: Any):
        """Set a specific value in a section."""
        if section not in self._config:
            self._config[section] = {}
        self._config[section][key] = value
        self._notify_change()
        self.save()  # Auto-save

    # =========================================================================
    # Code Generation - Generate theme.rpy
    # =========================================================================

    def generate_theme_rpy(self) -> str:
        """Generate the theme.rpy file content."""
        lines = []

        # Header
        lines.append("## theme.rpy - Generated by Preset Editor Game Configurator")
        lines.append("## This file overrides default gui.rpy and options.rpy settings")
        lines.append("## Delete this file to revert to Ren'Py defaults")
        lines.append("##")
        lines.append(f"## Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        lines.append("init offset = 1  # Load after gui.rpy")
        lines.append("")

        # Project section
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Project")
        lines.append("################################################################################")
        lines.append("")
        project = self._config.get("project", {})
        if project.get("name"):
            lines.append(f'define config.name = _("{project["name"]}")')
        if project.get("version"):
            lines.append(f'define config.version = "{project["version"]}"')
        if project.get("build_name"):
            lines.append(f'define build.name = "{project["build_name"]}"')
        if project.get("save_directory"):
            lines.append(f'define config.save_directory = "{project["save_directory"]}"')

        # Screen section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Screen Dimensions")
        lines.append("################################################################################")
        lines.append("")
        screen = self._config.get("screen", {})
        if screen.get("width"):
            lines.append(f'define config.screen_width = {screen["width"]}')
        if screen.get("height"):
            lines.append(f'define config.screen_height = {screen["height"]}')
        if screen.get("physical_width"):
            lines.append(f'define config.physical_width = {screen["physical_width"]}')
        if screen.get("physical_height"):
            lines.append(f'define config.physical_height = {screen["physical_height"]}')

        # Colors section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Colors")
        lines.append("################################################################################")
        lines.append("")
        colors = self._config.get("colors", {})
        color_map = [
            ("accent", "gui.accent_color"),
            ("hover", "gui.hover_color"),
            ("idle", "gui.idle_color"),
            ("idle_small", "gui.idle_small_color"),
            ("selected", "gui.selected_color"),
            ("insensitive", "gui.insensitive_color"),
            ("text", "gui.text_color"),
            ("interface_text", "gui.interface_text_color"),
            ("muted", "gui.muted_color"),
            ("hover_muted", "gui.hover_muted_color"),
        ]
        for json_key, rpy_var in color_map:
            if colors.get(json_key):
                lines.append(f"define {rpy_var} = '{colors[json_key]}'")

        # Fonts section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Fonts")
        lines.append("################################################################################")
        lines.append("")
        fonts = self._config.get("fonts", {})
        if fonts.get("text"):
            lines.append(f'define gui.text_font = "{fonts["text"]}"')
        if fonts.get("name"):
            lines.append(f'define gui.name_text_font = "{fonts["name"]}"')
        if fonts.get("interface"):
            lines.append(f'define gui.interface_text_font = "{fonts["interface"]}"')

        # Font sizes section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Font Sizes")
        lines.append("################################################################################")
        lines.append("")
        sizes = self._config.get("font_sizes", {})
        size_map = [
            ("text", "gui.text_size"),
            ("name", "gui.name_text_size"),
            ("interface", "gui.interface_text_size"),
            ("label", "gui.label_text_size"),
            ("notify", "gui.notify_text_size"),
            ("title", "gui.title_text_size"),
        ]
        for json_key, rpy_var in size_map:
            if sizes.get(json_key) is not None:
                lines.append(f"define {rpy_var} = {sizes[json_key]}")

        # Dialogue section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Dialogue Box Layout")
        lines.append("################################################################################")
        lines.append("")
        dialogue = self._config.get("dialogue", {})
        if dialogue.get("textbox_height") is not None:
            lines.append(f'define gui.textbox_height = {dialogue["textbox_height"]}')
        if dialogue.get("textbox_yalign") is not None:
            lines.append(f'define gui.textbox_yalign = {dialogue["textbox_yalign"]}')
        if dialogue.get("text_xpos") is not None:
            lines.append(f'define gui.dialogue_xpos = {dialogue["text_xpos"]}')
        if dialogue.get("text_ypos") is not None:
            lines.append(f'define gui.dialogue_ypos = {dialogue["text_ypos"]}')
        if dialogue.get("text_width") is not None:
            lines.append(f'define gui.dialogue_width = {dialogue["text_width"]}')
        if dialogue.get("text_xalign") is not None:
            lines.append(f'define gui.dialogue_text_xalign = {dialogue["text_xalign"]}')

        # Namebox section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Name Box Layout")
        lines.append("################################################################################")
        lines.append("")
        namebox = self._config.get("namebox", {})
        if namebox.get("xpos") is not None:
            lines.append(f'define gui.name_xpos = {namebox["xpos"]}')
        if namebox.get("ypos") is not None:
            lines.append(f'define gui.name_ypos = {namebox["ypos"]}')
        if namebox.get("xalign") is not None:
            lines.append(f'define gui.name_xalign = {namebox["xalign"]}')
        if namebox.get("width") is not None:
            lines.append(f'define gui.namebox_width = {namebox["width"]}')
        else:
            lines.append("# gui.namebox_width = None (using default)")
        if namebox.get("height") is not None:
            lines.append(f'define gui.namebox_height = {namebox["height"]}')
        else:
            lines.append("# gui.namebox_height = None (using default)")

        # Menu backgrounds section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Menu Backgrounds")
        lines.append("################################################################################")
        lines.append("")
        menus = self._config.get("menu_backgrounds", {})
        if menus.get("main_menu"):
            lines.append(f'define gui.main_menu_background = "{menus["main_menu"]}"')
        if menus.get("game_menu"):
            lines.append(f'define gui.game_menu_background = "{menus["game_menu"]}"')

        # Text speed section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Text Speed")
        lines.append("################################################################################")
        lines.append("")
        speed = self._config.get("text_speed", {})
        if speed.get("cps") is not None:
            lines.append(f'default preferences.text_cps = {speed["cps"]}')
        if speed.get("afm_time") is not None:
            lines.append(f'default preferences.afm_time = {speed["afm_time"]}')

        # Window behavior section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Window Behavior")
        lines.append("################################################################################")
        lines.append("")
        window = self._config.get("window_behavior", {})
        quit_confirm = window.get("quit_confirm", True)
        lines.append(f'define config.quit_action = Quit(confirm={quit_confirm})')
        if window.get("quit_message"):
            # Escape special characters for Ren'Py string
            msg = window["quit_message"]
            msg = msg.replace('\\', '\\\\')  # Escape backslashes first
            msg = msg.replace('"', '\\"')    # Escape quotes
            msg = msg.replace('\n', '\\n')   # Escape actual newlines
            lines.append(f'define gui.QUIT = _("{msg}")')

        # UI Details section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## UI Details")
        lines.append("################################################################################")
        lines.append("")
        ui = self._config.get("ui_details", {})
        if ui.get("bar_size") is not None:
            lines.append(f'define gui.bar_size = {ui["bar_size"]}')
        if ui.get("scrollbar_size") is not None:
            lines.append(f'define gui.scrollbar_size = {ui["scrollbar_size"]}')
        if ui.get("slider_size") is not None:
            lines.append(f'define gui.slider_size = {ui["slider_size"]}')
        if ui.get("button_width") is not None:
            lines.append(f'define gui.button_width = {ui["button_width"]}')
        else:
            lines.append("# gui.button_width = None (using default)")
        if ui.get("button_height") is not None:
            lines.append(f'define gui.button_height = {ui["button_height"]}')
        else:
            lines.append("# gui.button_height = None (using default)")
        # Button colors (only if set)
        for key in ["button_text_idle_color", "button_text_hover_color",
                    "button_text_selected_color", "button_text_insensitive_color"]:
            if ui.get(key):
                rpy_var = f"gui.{key}"
                lines.append(f"define {rpy_var} = '{ui[key]}'")

        # Choice buttons section
        lines.append("")
        lines.append("")
        lines.append("################################################################################")
        lines.append("## Choice Buttons")
        lines.append("################################################################################")
        lines.append("")
        choice = self._config.get("choice_buttons", {})
        if choice.get("width") is not None:
            lines.append(f'define gui.choice_button_width = {choice["width"]}')
        if choice.get("height") is not None:
            lines.append(f'define gui.choice_button_height = {choice["height"]}')
        else:
            lines.append("# gui.choice_button_height = None (using default)")
        if choice.get("text_idle_color"):
            lines.append(f"define gui.choice_button_text_idle_color = '{choice['text_idle_color']}'")
        if choice.get("text_hover_color"):
            lines.append(f"define gui.choice_button_text_hover_color = '{choice['text_hover_color']}'")
        if choice.get("text_insensitive_color"):
            lines.append(f"define gui.choice_button_text_insensitive_color = '{choice['text_insensitive_color']}'")
        if choice.get("spacing") is not None:
            lines.append(f'define gui.choice_spacing = {choice["spacing"]}')

        lines.append("")
        return "\n".join(lines)

    def export_theme_rpy(self, target_folder: str) -> bool:
        """Export theme.rpy to the target game folder."""
        if not target_folder:
            print("No target folder specified")
            return False

        target_path = Path(target_folder) / "theme.rpy"

        try:
            content = self.generate_theme_rpy()
            with open(target_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Exported theme.rpy to: {target_path}")

            # Update meta timestamp
            if "_meta" not in self._config:
                self._config["_meta"] = {}
            self._config["_meta"]["generated"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            self.save()

            return True
        except Exception as e:
            print(f"Error exporting theme.rpy: {e}")
            return False

    # =========================================================================
    # Section-specific getters for convenience
    # =========================================================================

    def get_project(self) -> Dict[str, Any]:
        return self.get_section("project") or {}

    def get_screen(self) -> Dict[str, Any]:
        return self.get_section("screen") or {}

    def get_colors(self) -> Dict[str, Any]:
        return self.get_section("colors") or {}

    def get_fonts(self) -> Dict[str, Any]:
        return self.get_section("fonts") or {}

    def get_font_sizes(self) -> Dict[str, Any]:
        return self.get_section("font_sizes") or {}

    def get_dialogue(self) -> Dict[str, Any]:
        return self.get_section("dialogue") or {}

    def get_namebox(self) -> Dict[str, Any]:
        return self.get_section("namebox") or {}

    def get_menu_backgrounds(self) -> Dict[str, Any]:
        return self.get_section("menu_backgrounds") or {}

    def get_text_speed(self) -> Dict[str, Any]:
        return self.get_section("text_speed") or {}

    def get_window_behavior(self) -> Dict[str, Any]:
        return self.get_section("window_behavior") or {}

    def get_ui_details(self) -> Dict[str, Any]:
        return self.get_section("ui_details") or {}

    def get_choice_buttons(self) -> Dict[str, Any]:
        return self.get_section("choice_buttons") or {}
